# Site
repository: rklearns/rklearns.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Rishit Kar
title: Aspiring AI Engineer
email: emailrishitkar@gmail.com
website: https://github.com/rklearns

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: rklearns
linkedin_username: rishit-kar-786495286

# Additional icon links
additional_links:
- title: LeetCode
  icon: fas fa-code
  url: https://leetcode.com/u/Rkstriker/
- title: Codeforces
  icon: fas fa-trophy
  url: https://codeforces.com/profile/emailrishitkar

# About Section
about_profile_image: imgs/profile1.jpg
about_content: | # this will include new lines to allow paragraphs
  I am Rishit Kar, a third-year undergraduate student at DJ Sanghvi College of Engineering, Mumbai University, with a strong passion for **research and innovation in Artificial Intelligence**. My academic journey is driven by a deep curiosity to explore how AI can address complex, real-world challenges across diverse domains.

  Through my research collaborations with prestigious institutions like IIT Patna and IIT Mandi, I have gained hands-on experience in developing sophisticated AI solutions. My work spans from building explainable deep learning models for medical imaging to implementing geometric deep learning architectures for engineering optimization problems.

  I have also had some experience in competitive programming, holding **Pupil rank on Codeforces** and **3-star rating on CodeChef**, which has strengthened my problem-solving abilities and algorithmic thinking.

  My tech interests and learning focus areas include:

  - **Explainable AI for Healthcare Applications**
  - **Large Language Models for Natural Language Understanding**
  - **Computer Vision for Medical Imaging**
  - **Data Engineering for ML Pipelines**
  - **Backend Systems for AI Applications**
  - **Open Source Contributions to ML Frameworks**

  My approach combines rigorous theoretical understanding with practical implementation, always emphasizing the importance of explainability and real-world applicability in AI systems.

content:
  - title: Education
    layout: list
    content:
      - layout: left
        title: Dwarkadas Jivanlal Sanghvi College Of Engineering, Mumbai
        caption: 2023 - 2027, CGPA- 9.14
        sub_title: BTech, Computer Engineering
        description: |
          **Coursework:** Artificial Intelligence, Compiler Design and Automata, Advanced Database Management Systems, Database Management Systems, Operating Systems, Data Structures, Analysis of Algorithms, Python Programming, Object-Oriented Programming Systems
          
          **Position of Responsibility:**
          
          **Research Head at DJS ACM** - Guiding students about research opportunities, conducting meetings to mentor students in machine learning and AI research, and facilitating research collaboration opportunities within the college community.

  - title: Experience
    layout: list
    content:
      - layout: left
        title: Indian Institute of Technology Patna
        sub_title: Research Collaborator - Deep Learning for Medical Imaging
        caption: August 2025 - Present
        description: |
          • Developing deep learning models for comprehensive analysis of NIH chest X-ray datasets
          
          • Focusing on explainability and clinical interpretability for medical AI applications
          
          • Ensuring transparent and interpretable AI-driven medical decision-making processes

          **Supervised by Dr. Joydeep Chandra**

      - layout: left
        title: sktime
        link: https://www.sktime.net/en/stable/
        sub_title: Open Source Contributor
        caption: August 2025 - Present
        description: |
          • Contributing to sktime, a unified framework for machine learning with time series data in Python
          
          • Working on pull requests for migration of TensorFlow implementations to PyTorch
          
          • Helping migrate deep learning components to improve framework consistency
          
          • Supporting the open source community with code improvements and framework enhancements

      - layout: left
        title: Indian Institute of Technology Mandi (Onsite)
        sub_title: Research Intern - Machine Learning for Propeller Optimization
        caption: June 2025 - July 2025
        description: |
          • Collaborated at the **Center for Artificial Intelligence and Robotics (CAIR Lab)**
          
          • Conducted extensive literature review on geometric deep learning methodologies
          
          • Successfully implemented Dynamic Graph Convolutional Neural Network (DGCNN) architecture
          
          • Performed comprehensive data analysis and feature engineering on complex 3D propeller datasets

          **Supervised by Dr. Jagadeesh Kadiyam**

  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: Deep Learning for Multiomics Cancer Subtyping (Ongoing)
        additional_links:
          - title: College Research Project
        quote: >
          Advanced deep learning models for cancer group subtyping using multiomics data
        description: |
          Currently developing sophisticated deep learning architectures for analyzing multiomics datasets to perform cancer group subtyping across different cancer types using <mark>unsupervised learning</mark>, <mark>Variational Autoencoder</mark> and <mark>explainable AI</mark>. Working with integrated genomic data including mRNA expression, copy number variations, and methylation patterns. Implementing novel neural network approaches to identify distinct cancer subtypes and improve diagnostic precision in oncological applications using <mark>PyTorch</mark> and <mark>scikit-learn</mark>.

      - layout: top-middle
        title: Clipper-dev
        additional_links:
          - title: Rklearns/clipper-dev
            icon: fab fa-github
            url: https://github.com/Rklearns/clipper-dev
        quote: >
          The Ultimate Cross-Platform Clipboard Manager for Developers
        description: |
          Developed a comprehensive clipboard management tool with <mark>terminal user interface</mark> and published it as a <mark>Python package on PyPI</mark>. Built using <mark>Python</mark> with integrated <mark>TUI capabilities</mark> for enhanced developer productivity. Implemented <mark>fuzzy search</mark> functionality, real-time monitoring, and cross-platform compatibility. Used <mark>pytest</mark> for comprehensive testing and achieved proper package distribution through PyPI.

      - layout: top-middle
        title: Multi-Model Pneumonia Diagnosis
        additional_links:
          - title: View Project
            icon: fab fa-github
            url: https://github.com/Rklearns/Chest-X-Ray-Detection
        quote: >
          Deep learning ensemble for medical image classification using CNN, ResNet, and Graph Neural Networks
        description: |
          Built a comprehensive deep learning solution for pneumonia classification using chest X-ray images. Implemented <mark>custom CNN architecture</mark> alongside <mark>ResNet</mark> and <mark>Graph Attention Network (GAT)</mark> models for comparative analysis. Developed <mark>multimodal learning pipeline</mark> integrating spatial and attention-based features. Achieved high test accuracy with strong F1 scores for clinical reliability using <mark>TensorFlow</mark> and <mark>Keras</mark>.

      - layout: top-middle
        title: Custom Reliable UDP Protocol
        additional_links:
          - title: View Project
            icon: fab fa-github
            url: https://github.com/Rklearns/Custom-Protocol-Architecture
        quote: >
          High-performance reliable transport protocol with sliding window flow control
        description: |
          Engineered a reliable transport protocol from scratch using <mark>Python UDP sockets</mark>, incorporating TCP-like features including <mark>sliding window flow control</mark> and automatic retransmission. Implemented <mark>SHA-256 checksums</mark> for data integrity and <mark>concurrent packet processing</mark>. Achieved significant performance improvements over traditional stop-and-wait protocols through optimized throughput testing.

      - layout: top-middle
        title: URL-Detracker VS Code Extension
        additional_links:
          - title: GitHub Repository
            icon: fab fa-github
            url: https://github.com/Rklearns/url-detracker
        quote: >
          Privacy-focused VS Code extension for cleaning tracking parameters from URLs
        description: |
          Created and published a <mark>VS Code extension</mark> that automatically removes tracking parameters from URLs on paste, enhancing user privacy and link readability. Implemented offline functionality using <mark>regex patterns</mark> without external dependencies. Built using <mark>JavaScript</mark> and <mark>VS Code API</mark>, with comprehensive documentation and marketplace compatibility.

  - title: Skills
    layout: list
    content:
      - layout: left
        title: Programming Languages
        description: |
          • **Python** - Advanced proficiency in data science, machine learning, and backend development
          
          • **Java** - Object-oriented programming and application development
          
          • **JavaScript** - Frontend development and VS Code extension creation
          
          • **C** - System programming and algorithm implementation
          
          • **SQL (MySQL)** - Database design, querying, and optimization
          
          • **HTML/CSS** - Web development and user interface design

      - layout: left
        title: Machine Learning & AI
        description: |
          • **Deep Learning Frameworks** - TensorFlow, Keras, PyTorch
          
          • **ML Libraries** - Scikit-Learn, Pandas, NumPy, Matplotlib
          
          • **Computer Vision** - OpenCV, MediaPipe for image processing and gesture recognition
          
          • **Specialized Models** - CNN, ResNet, Graph Neural Networks, Variational Autoencoders
          
          • **Data Analysis** - Feature engineering, model evaluation, and performance optimization

      - layout: left
        title: Developer Tools & Platforms
        description: |
          • **Version Control** - Git, GitHub for collaborative development
          
          • **Development Environment** - VS Code, Visual Studio, Google Colab, Jupyter Notebooks
          
          • **Cloud & Deployment** - Vercel, Streamlit for application deployment
          
          • **Package Management** - PyPI package development and distribution
          
          • **Testing** - pytest for comprehensive testing frameworks

      - layout: left
        title: Technical Knowledge
        description: |
          • **Operating Systems** - System-level programming and OS concepts
          
          • **Database Management** - DBMS design, Advanced DBMS, and database optimization
          
          • **Network Programming** - UDP/TCP protocols, socket programming
          
          • **Data Structures & Algorithms** - Algorithm analysis and competitive programming
          
          • **Software Engineering** - Code architecture, design patterns, and best practices

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
